const assets = [
	{
	"id":"base-gradient",
	"url":"assets/image\\base-gradient.png"
	},
	{
	"id":"bigblur",
	"url":"assets/image\\bigblur.png"
	},
	{
	"id":"glass",
	"url":"assets/image\\glass.png"
	},
	{
	"id":"image",
	"url":"assets/image\\image.png"
	},
	{
	"id":"lane_texture - Copy",
	"url":"assets/image\\lane_texture - Copy.png"
	},
	{
	"id":"lettering",
	"url":"assets/image\\lettering.png"
	},
	{
	"id":"lane_texture",
	"url":"assets/image\\lane_texture.png"
	},
	{
	"id":"logo",
	"url":"assets/image\\logo.png"
	},
	{
	"id":"logo_mask",
	"url":"assets/image\\logo_mask.png"
	},
	{
	"id":"logo_mask_white",
	"url":"assets/image\\logo_mask_white.png"
	},
	{
	"id":"pattern",
	"url":"assets/image\\pattern.png"
	},
	{
	"id":"planet",
	"url":"assets/image\\planet.png"
	},
	{
	"id":"planet2",
	"url":"assets/image\\planet2.png"
	},
	{
	"id":"planet1",
	"url":"assets/image\\planet1.png"
	},
	{
	"id":"planet3",
	"url":"assets/image\\planet3.png"
	},
	{
	"id":"planet4",
	"url":"assets/image\\planet4.png"
	},
	{
	"id":"vignette-tex",
	"url":"assets/image\\vignette-tex.png"
	},
	{
	"id":"vignette-tex2",
	"url":"assets/image\\vignette-tex2.png"
	},
	{
	"id":"vignette",
	"url":"assets/image\\vignette.png"
	},
	{
	"id":"spark2",
	"url":"assets/image\\particles\\spark2.png"
	},
	{
	"id":"pickup_bubble",
	"url":"assets/image\\pickups\\pickup_bubble.png"
	},
	{
	"id":"pickup_fish",
	"url":"assets/image\\pickups\\pickup_fish.png"
	},
	{
	"id":"pickup_mouse",
	"url":"assets/image\\pickups\\pickup_mouse.png"
	},
	{
	"id":"pickup_octopus",
	"url":"assets/image\\pickups\\pickup_octopus.png"
	},
	{
	"id":"active_engine",
	"url":"assets/image\\ui\\active_engine.png"
	},
	{
	"id":"automate",
	"url":"assets/image\\ui\\automate.png"
	},
	{
	"id":"auto_confirm",
	"url":"assets/image\\ui\\auto_confirm.png"
	},
	{
	"id":"bubble",
	"url":"assets/image\\ui\\bubble.png"
	},
	{
	"id":"back_button",
	"url":"assets/image\\ui\\back_button.png"
	},
	{
	"id":"button_off",
	"url":"assets/image\\ui\\button_off.png"
	},
	{
	"id":"button_on",
	"url":"assets/image\\ui\\button_on.png"
	},
	{
	"id":"buy_grey",
	"url":"assets/image\\ui\\buy_grey.png"
	},
	{
	"id":"cat_coin",
	"url":"assets/image\\ui\\cat_coin.png"
	},
	{
	"id":"buy_icon",
	"url":"assets/image\\ui\\buy_icon.png"
	},
	{
	"id":"cat_coin_02",
	"url":"assets/image\\ui\\cat_coin_02.png"
	},
	{
	"id":"coin_pig",
	"url":"assets/image\\ui\\coin_pig.png"
	},
	{
	"id":"deactive_engine",
	"url":"assets/image\\ui\\deactive_engine.png"
	},
	{
	"id":"discount",
	"url":"assets/image\\ui\\discount.png"
	},
	{
	"id":"engine_icon",
	"url":"assets/image\\ui\\engine_icon.png"
	},
	{
	"id":"game_button_base",
	"url":"assets/image\\ui\\game_button_base.png"
	},
	{
	"id":"game_button_base_borderless",
	"url":"assets/image\\ui\\game_button_base_borderless.png"
	},
	{
	"id":"game_button_base_borderless_green",
	"url":"assets/image\\ui\\game_button_base_borderless_green.png"
	},
	{
	"id":"game_button_off",
	"url":"assets/image\\ui\\game_button_off.png"
	},
	{
	"id":"game_button_on",
	"url":"assets/image\\ui\\game_button_on.png"
	},
	{
	"id":"goodboy",
	"url":"assets/image\\ui\\goodboy.png"
	},
	{
	"id":"icon_back",
	"url":"assets/image\\ui\\icon_back.png"
	},
	{
	"id":"icon_border",
	"url":"assets/image\\ui\\icon_border.png"
	},
	{
	"id":"goodboy_logo",
	"url":"assets/image\\ui\\goodboy_logo.png"
	},
	{
	"id":"icon_close",
	"url":"assets/image\\ui\\icon_close.png"
	},
	{
	"id":"icon_confirm",
	"url":"assets/image\\ui\\icon_confirm.png"
	},
	{
	"id":"icon_duration_blue",
	"url":"assets/image\\ui\\icon_duration_blue.png"
	},
	{
	"id":"icon_duration_orange",
	"url":"assets/image\\ui\\icon_duration_orange.png"
	},
	{
	"id":"icon_duration_green",
	"url":"assets/image\\ui\\icon_duration_green.png"
	},
	{
	"id":"icon_increase",
	"url":"assets/image\\ui\\icon_increase.png"
	},
	{
	"id":"icon_lives",
	"url":"assets/image\\ui\\icon_lives.png"
	},
	{
	"id":"icon_paw",
	"url":"assets/image\\ui\\icon_paw.png"
	},
	{
	"id":"icon_play",
	"url":"assets/image\\ui\\icon_play.png"
	},
	{
	"id":"icon_shop",
	"url":"assets/image\\ui\\icon_shop.png"
	},
	{
	"id":"info",
	"url":"assets/image\\ui\\info.png"
	},
	{
	"id":"morecats",
	"url":"assets/image\\ui\\morecats.png"
	},
	{
	"id":"play button_large_over",
	"url":"assets/image\\ui\\play button_large_over.png"
	},
	{
	"id":"play button_large_up",
	"url":"assets/image\\ui\\play button_large_up.png"
	},
	{
	"id":"powerbar_bar",
	"url":"assets/image\\ui\\powerbar_bar.png"
	},
	{
	"id":"powerbar_border",
	"url":"assets/image\\ui\\powerbar_border.png"
	},
	{
	"id":"progressbar_frame",
	"url":"assets/image\\ui\\progressbar_frame.png"
	},
	{
	"id":"progressbar_bar",
	"url":"assets/image\\ui\\progressbar_bar.png"
	},
	{
	"id":"results_arrow",
	"url":"assets/image\\ui\\results_arrow.png"
	},
	{
	"id":"results_lock",
	"url":"assets/image\\ui\\results_lock.png"
	},
	{
	"id":"results_locked_cat",
	"url":"assets/image\\ui\\results_locked_cat.png"
	},
	{
	"id":"results_newcat_glow",
	"url":"assets/image\\ui\\results_newcat_glow.png"
	},
	{
	"id":"results_newcat_rays_01",
	"url":"assets/image\\ui\\results_newcat_rays_01.png"
	},
	{
	"id":"results_newcat_rays_02",
	"url":"assets/image\\ui\\results_newcat_rays_02.png"
	},
	{
	"id":"results_newcat_star",
	"url":"assets/image\\ui\\results_newcat_star.png"
	},
	{
	"id":"results_orange_cat",
	"url":"assets/image\\ui\\results_orange_cat.png"
	},
	{
	"id":"results_pink_cat",
	"url":"assets/image\\ui\\results_pink_cat.png"
	},
	{
	"id":"results_turquoise_cat",
	"url":"assets/image\\ui\\results_turquoise_cat.png"
	},
	{
	"id":"results_yellow_cat",
	"url":"assets/image\\ui\\results_yellow_cat.png"
	},
	{
	"id":"rocket_button_off",
	"url":"assets/image\\ui\\rocket_button_off.png"
	},
	{
	"id":"rollerskate",
	"url":"assets/image\\ui\\rollerskate.png"
	},
	{
	"id":"rocket_button_over",
	"url":"assets/image\\ui\\rocket_button_over.png"
	},
	{
	"id":"round_back",
	"url":"assets/image\\ui\\round_back.png"
	},
	{
	"id":"score_plinth",
	"url":"assets/image\\ui\\score_plinth.png"
	},
	{
	"id":"shop_button",
	"url":"assets/image\\ui\\shop_button.png"
	},
	{
	"id":"spaceship",
	"url":"assets/image\\ui\\spaceship.png"
	},
	{
	"id":"text_auto_rescue",
	"url":"assets/image\\ui\\text_auto_rescue.png"
	},
	{
	"id":"text_catnip_frenzy",
	"url":"assets/image\\ui\\text_catnip_frenzy.png"
	},
	{
	"id":"token_grey",
	"url":"assets/image\\ui\\token_grey.png"
	},
	{
	"id":"token_price",
	"url":"assets/image\\ui\\token_price.png"
	},
	{
	"id":"token_quant",
	"url":"assets/image\\ui\\token_quant.png"
	},
	{
	"id":"treasure_chest",
	"url":"assets/image\\ui\\treasure_chest.png"
	},
	{
	"id":"treasure_chest_01",
	"url":"assets/image\\ui\\treasure_chest_01.png"
	},
	{
	"id":"treasure_chest_02",
	"url":"assets/image\\ui\\treasure_chest_02.png"
	},
	{
	"id":"trophy",
	"url":"assets/image\\ui\\trophy.png"
	},
	{
	"id":"treasure_chest_03",
	"url":"assets/image\\ui\\treasure_chest_03.png"
	},
	{
	"id":"ui_bg",
	"url":"assets/image\\ui\\ui_bg.png"
	},
	{
	"id":"video_icon",
	"url":"assets/image\\ui\\video_icon.png"
	},
	{
	"id":"helmet",
	"url":"assets/image\\cats\\helmet.png"
	},
	{
	"id":"cat_orange_body",
	"url":"assets/image\\cats\\orange_cat\\cat_orange_body.png"
	},
	{
	"id":"cat_orange_arm",
	"url":"assets/image\\cats\\orange_cat\\cat_orange_arm.png"
	},
	{
	"id":"cat_orange_head_01",
	"url":"assets/image\\cats\\orange_cat\\cat_orange_head_01.png"
	},
	{
	"id":"cat_orange_head_02",
	"url":"assets/image\\cats\\orange_cat\\cat_orange_head_02.png"
	},
	{
	"id":"cat_orange_head_03",
	"url":"assets/image\\cats\\orange_cat\\cat_orange_head_03.png"
	},
	{
	"id":"cat_orange_leg",
	"url":"assets/image\\cats\\orange_cat\\cat_orange_leg.png"
	},
	{
	"id":"cat_pink_arm",
	"url":"assets/image\\cats\\pink_cat\\cat_pink_arm.png"
	},
	{
	"id":"cat_pink_body",
	"url":"assets/image\\cats\\pink_cat\\cat_pink_body.png"
	},
	{
	"id":"cat_pink_head_01",
	"url":"assets/image\\cats\\pink_cat\\cat_pink_head_01.png"
	},
	{
	"id":"cat_pink_head_03",
	"url":"assets/image\\cats\\pink_cat\\cat_pink_head_03.png"
	},
	{
	"id":"cat_pink_head_02",
	"url":"assets/image\\cats\\pink_cat\\cat_pink_head_02.png"
	},
	{
	"id":"cat_pink_leg",
	"url":"assets/image\\cats\\pink_cat\\cat_pink_leg.png"
	},
	{
	"id":"white_arm",
	"url":"assets/image\\cats\\white_cat\\white_arm.png"
	},
	{
	"id":"white_body",
	"url":"assets/image\\cats\\white_cat\\white_body.png"
	},
	{
	"id":"white_leg",
	"url":"assets/image\\cats\\white_cat\\white_leg.png"
	},
	{
	"id":"white_head_01",
	"url":"assets/image\\cats\\white_cat\\white_head_01.png"
	},
	{
	"id":"cat_turquoise_arm",
	"url":"assets/image\\cats\\turquoise_cat\\cat_turquoise_arm.png"
	},
	{
	"id":"cat_turquoise_body",
	"url":"assets/image\\cats\\turquoise_cat\\cat_turquoise_body.png"
	},
	{
	"id":"cat_turquoise_head_01",
	"url":"assets/image\\cats\\turquoise_cat\\cat_turquoise_head_01.png"
	},
	{
	"id":"cat_turquoise_head_02",
	"url":"assets/image\\cats\\turquoise_cat\\cat_turquoise_head_02.png"
	},
	{
	"id":"cat_turquoise_head_03",
	"url":"assets/image\\cats\\turquoise_cat\\cat_turquoise_head_03.png"
	},
	{
	"id":"cat_turquoise_leg",
	"url":"assets/image\\cats\\turquoise_cat\\cat_turquoise_leg.png"
	},
	{
	"id":"cat_yellow_arm",
	"url":"assets/image\\cats\\yellow_cat\\cat_yellow_arm.png"
	},
	{
	"id":"cat_yellow_body",
	"url":"assets/image\\cats\\yellow_cat\\cat_yellow_body.png"
	},
	{
	"id":"cat_yellow_head_01",
	"url":"assets/image\\cats\\yellow_cat\\cat_yellow_head_01.png"
	},
	{
	"id":"cat_yellow_head_02",
	"url":"assets/image\\cats\\yellow_cat\\cat_yellow_head_02.png"
	},
	{
	"id":"cat_yellow_head_03",
	"url":"assets/image\\cats\\yellow_cat\\cat_yellow_head_03.png"
	},
	{
	"id":"cat_yellow_leg",
	"url":"assets/image\\cats\\yellow_cat\\cat_yellow_leg.png"
	}
];

export default assets;
