const assets = [
	{
	"id":"1",
	"url":"assets/audio/1.wav"
	},
	{
	"id":"2",
	"url":"assets/audio/2.wav"
	},
	{
	"id":"3",
	"url":"assets/audio/3.wav"
	},
	{
	"id":"blam_a",
	"url":"assets/audio/blam_a.mp3"
	},
	{
	"id":"blaaaaam",
	"url":"assets/audio/blaaaaam.mp3"
	},
	{
	"id":"blam_b",
	"url":"assets/audio/blam_b.mp3"
	},
	{
	"id":"blam_l",
	"url":"assets/audio/blam_l.mp3"
	},
	{
	"id":"blam_m",
	"url":"assets/audio/blam_m.mp3"
	},
	{
	"id":"button_click",
	"url":"assets/audio/button_click.mp3"
	},
	{
	"id":"boing",
	"url":"assets/audio/boing.mp3"
	},
	{
	"id":"cat_01",
	"url":"assets/audio/cat_01.mp3"
	},
	{
	"id":"cat_02",
	"url":"assets/audio/cat_02.mp3"
	},
	{
	"id":"cat_03",
	"url":"assets/audio/cat_03.mp3"
	},
	{
	"id":"cat_05",
	"url":"assets/audio/cat_05.mp3"
	},
	{
	"id":"cat_04",
	"url":"assets/audio/cat_04.mp3"
	},
	{
	"id":"cat_06",
	"url":"assets/audio/cat_06.mp3"
	},
	{
	"id":"cat_07",
	"url":"assets/audio/cat_07.mp3"
	},
	{
	"id":"cat_08",
	"url":"assets/audio/cat_08.mp3"
	},
	{
	"id":"cat_10",
	"url":"assets/audio/cat_10.mp3"
	},
	{
	"id":"cat_09",
	"url":"assets/audio/cat_09.mp3"
	},
	{
	"id":"coins_01",
	"url":"assets/audio/coins_01.mp3"
	},
	{
	"id":"coins_02",
	"url":"assets/audio/coins_02.mp3"
	},
	{
	"id":"coins_03",
	"url":"assets/audio/coins_03.mp3"
	},
	{
	"id":"coins_04",
	"url":"assets/audio/coins_04.mp3"
	},
	{
	"id":"crash",
	"url":"assets/audio/crash.mp3"
	},
	{
	"id":"crate_smash",
	"url":"assets/audio/crate_smash.mp3"
	},
	{
	"id":"dennis_8bitloop_short",
	"url":"assets/audio/dennis_8bitloop_short.mp3"
	},
	{
	"id":"dennis_music_loop_01",
	"url":"assets/audio/dennis_music_loop_01.mp3"
	},
	{
	"id":"dennis_8bit_loop",
	"url":"assets/audio/dennis_8bit_loop.mp3"
	},
	{
	"id":"dennis_music_loop_02",
	"url":"assets/audio/dennis_music_loop_02.mp3"
	},
	{
	"id":"dennis_music_loop_04",
	"url":"assets/audio/dennis_music_loop_04.mp3"
	},
	{
	"id":"dennis_music_loop_07",
	"url":"assets/audio/dennis_music_loop_07.mp3"
	},
	{
	"id":"dennis_music_loop_08",
	"url":"assets/audio/dennis_music_loop_08.mp3"
	},
	{
	"id":"dennis_music_loop_09",
	"url":"assets/audio/dennis_music_loop_09.mp3"
	},
	{
	"id":"dream1",
	"url":"assets/audio/dream1.mp3"
	},
	{
	"id":"dream2",
	"url":"assets/audio/dream2.mp3"
	},
	{
	"id":"finishline",
	"url":"assets/audio/finishline.mp3"
	},
	{
	"id":"fireworks",
	"url":"assets/audio/fireworks.mp3"
	},
	{
	"id":"footsteps_concrete",
	"url":"assets/audio/footsteps_concrete.mp3"
	},
	{
	"id":"footsteps_metal",
	"url":"assets/audio/footsteps_metal.mp3"
	},
	{
	"id":"footsteps_wood",
	"url":"assets/audio/footsteps_wood.mp3"
	},
	{
	"id":"game_gameover",
	"url":"assets/audio/game_gameover.mp3"
	},
	{
	"id":"game_gameover_02",
	"url":"assets/audio/game_gameover_02.mp3"
	},
	{
	"id":"getstar",
	"url":"assets/audio/getstar.mp3"
	},
	{
	"id":"glass_smash_01",
	"url":"assets/audio/glass_smash_01.mp3"
	},
	{
	"id":"glass_smash_02",
	"url":"assets/audio/glass_smash_02.mp3"
	},
	{
	"id":"glass_smash_03",
	"url":"assets/audio/glass_smash_03.mp3"
	},
	{
	"id":"glass_smash_04",
	"url":"assets/audio/glass_smash_04.mp3"
	},
	{
	"id":"grind",
	"url":"assets/audio/grind.wav"
	},
	{
	"id":"jump",
	"url":"assets/audio/jump.mp3"
	},
	{
	"id":"jump2",
	"url":"assets/audio/jump2.mp3"
	},
	{
	"id":"land",
	"url":"assets/audio/land.mp3"
	},
	{
	"id":"music_results",
	"url":"assets/audio/music_results.mp3"
	},
	{
	"id":"paint_splash",
	"url":"assets/audio/paint_splash.mp3"
	},
	{
	"id":"pendulum_in",
	"url":"assets/audio/pendulum_in.mp3"
	},
	{
	"id":"pendulum_out",
	"url":"assets/audio/pendulum_out.mp3"
	},
	{
	"id":"poster_get",
	"url":"assets/audio/poster_get.mp3"
	},
	{
	"id":"pickup",
	"url":"assets/audio/pickup.mp3"
	},
	{
	"id":"rocket_launch_01",
	"url":"assets/audio/rocket_launch_01.mp3"
	},
	{
	"id":"rope_whoosh_01",
	"url":"assets/audio/rope_whoosh_01.mp3"
	},
	{
	"id":"rope_whoosh_02",
	"url":"assets/audio/rope_whoosh_02.mp3"
	},
	{
	"id":"seesaw",
	"url":"assets/audio/seesaw.mp3"
	},
	{
	"id":"score_loop",
	"url":"assets/audio/score_loop.mp3"
	},
	{
	"id":"slime_01",
	"url":"assets/audio/slime_01.mp3"
	},
	{
	"id":"spacecat_game_music",
	"url":"assets/audio/spacecat_game_music.mp3"
	},
	{
	"id":"teleport",
	"url":"assets/audio/teleport.mp3"
	},
	{
	"id":"tutorial_swipe",
	"url":"assets/audio/tutorial_swipe.mp3"
	},
	{
	"id":"wheel_land",
	"url":"assets/audio/wheel_land.mp3"
	},
	{
	"id":"wheel_loop",
	"url":"assets/audio/wheel_loop.mp3"
	}
];

export default assets;
