const assets = [
	{
	"id":"base-gradient",
	"url":"assets/image\\base-gradient.png"
	},
	{
	"id":"bigblur",
	"url":"assets/image\\bigblur.png"
	},
	{
	"id":"image",
	"url":"assets/image\\image.png"
	},
	{
	"id":"lane_texture - Copy",
	"url":"assets/image\\lane_texture - Copy.png"
	},
	{
	"id":"lane_texture",
	"url":"assets/image\\lane_texture.png"
	},
	{
	"id":"lettering",
	"url":"assets/image\\lettering.png"
	},
	{
	"id":"logo_mask",
	"url":"assets/image\\logo_mask.png"
	},
	{
	"id":"logo_mask_white",
	"url":"assets/image\\logo_mask_white.png"
	},
	{
	"id":"planet",
	"url":"assets/image\\planet.png"
	},
	{
	"id":"pattern",
	"url":"assets/image\\pattern.png"
	},
	{
	"id":"vignette-tex",
	"url":"assets/image\\vignette-tex.png"
	},
	{
	"id":"vignette-tex2",
	"url":"assets/image\\vignette-tex2.png"
	},
	{
	"id":"vignette",
	"url":"assets/image\\vignette.png"
	},
	{
	"id":"pickup_bubble",
	"url":"assets/image\\pickups\\pickup_bubble.png"
	},
	{
	"id":"spark2",
	"url":"assets/image\\particles\\spark2.png"
	},
	{
	"id":"active_engine",
	"url":"assets/image\\ui\\active_engine.png"
	},
	{
	"id":"back_button",
	"url":"assets/image\\ui\\back_button.png"
	},
	{
	"id":"automate",
	"url":"assets/image\\ui\\automate.png"
	},
	{
	"id":"auto_confirm",
	"url":"assets/image\\ui\\auto_confirm.png"
	},
	{
	"id":"button_collect_prizes_off",
	"url":"assets/image\\ui\\button_collect_prizes_off.png"
	},
	{
	"id":"bubble",
	"url":"assets/image\\ui\\bubble.png"
	},
	{
	"id":"button_collect_prizes_on",
	"url":"assets/image\\ui\\button_collect_prizes_on.png"
	},
	{
	"id":"button_off",
	"url":"assets/image\\ui\\button_off.png"
	},
	{
	"id":"button_on",
	"url":"assets/image\\ui\\button_on.png"
	},
	{
	"id":"buy_grey",
	"url":"assets/image\\ui\\buy_grey.png"
	},
	{
	"id":"buy_icon",
	"url":"assets/image\\ui\\buy_icon.png"
	},
	{
	"id":"cat_coin",
	"url":"assets/image\\ui\\cat_coin.png"
	},
	{
	"id":"cat_coin_02",
	"url":"assets/image\\ui\\cat_coin_02.png"
	},
	{
	"id":"cat_coin_particle",
	"url":"assets/image\\ui\\cat_coin_particle.png"
	},
	{
	"id":"cat_coin_particle_ingame",
	"url":"assets/image\\ui\\cat_coin_particle_ingame.png"
	},
	{
	"id":"coin_pig",
	"url":"assets/image\\ui\\coin_pig.png"
	},
	{
	"id":"deactive_engine",
	"url":"assets/image\\ui\\deactive_engine.png"
	},
	{
	"id":"discount",
	"url":"assets/image\\ui\\discount.png"
	},
	{
	"id":"engine_icon",
	"url":"assets/image\\ui\\engine_icon.png"
	},
	{
	"id":"fast_forward_icon",
	"url":"assets/image\\ui\\fast_forward_icon.png"
	},
	{
	"id":"fast_forward_noise",
	"url":"assets/image\\ui\\fast_forward_noise.png"
	},
	{
	"id":"game_button_base",
	"url":"assets/image\\ui\\game_button_base.png"
	},
	{
	"id":"game_button_off",
	"url":"assets/image\\ui\\game_button_off.png"
	},
	{
	"id":"game_button_on",
	"url":"assets/image\\ui\\game_button_on.png"
	},
	{
	"id":"giftbox",
	"url":"assets/image\\ui\\giftbox.png"
	},
	{
	"id":"giftbox2",
	"url":"assets/image\\ui\\giftbox2.png"
	},
	{
	"id":"goodboy",
	"url":"assets/image\\ui\\goodboy.png"
	},
	{
	"id":"goodboy_heart",
	"url":"assets/image\\ui\\goodboy_heart.png"
	},
	{
	"id":"goodboy_logo",
	"url":"assets/image\\ui\\goodboy_logo.png"
	},
	{
	"id":"goodboy_logo_square",
	"url":"assets/image\\ui\\goodboy_logo_square.png"
	},
	{
	"id":"icon_back",
	"url":"assets/image\\ui\\icon_back.png"
	},
	{
	"id":"icon_border",
	"url":"assets/image\\ui\\icon_border.png"
	},
	{
	"id":"icon_close",
	"url":"assets/image\\ui\\icon_close.png"
	},
	{
	"id":"icon_confirm",
	"url":"assets/image\\ui\\icon_confirm.png"
	},
	{
	"id":"icon_down",
	"url":"assets/image\\ui\\icon_down.png"
	},
	{
	"id":"icon_duration_blue",
	"url":"assets/image\\ui\\icon_duration_blue.png"
	},
	{
	"id":"icon_duration_green",
	"url":"assets/image\\ui\\icon_duration_green.png"
	},
	{
	"id":"icon_duration_orange",
	"url":"assets/image\\ui\\icon_duration_orange.png"
	},
	{
	"id":"icon_lives",
	"url":"assets/image\\ui\\icon_lives.png"
	},
	{
	"id":"icon_increase",
	"url":"assets/image\\ui\\icon_increase.png"
	},
	{
	"id":"icon_duration_pink",
	"url":"assets/image\\ui\\icon_duration_pink.png"
	},
	{
	"id":"icon_paw",
	"url":"assets/image\\ui\\icon_paw.png"
	},
	{
	"id":"icon_play",
	"url":"assets/image\\ui\\icon_play.png"
	},
	{
	"id":"icon_play_video",
	"url":"assets/image\\ui\\icon_play_video.png"
	},
	{
	"id":"icon_reset",
	"url":"assets/image\\ui\\icon_reset.png"
	},
	{
	"id":"icon_settings",
	"url":"assets/image\\ui\\icon_settings.png"
	},
	{
	"id":"icon_shop",
	"url":"assets/image\\ui\\icon_shop.png"
	},
	{
	"id":"icon_sound_off",
	"url":"assets/image\\ui\\icon_sound_off.png"
	},
	{
	"id":"icon_sound_on",
	"url":"assets/image\\ui\\icon_sound_on.png"
	},
	{
	"id":"icon_up",
	"url":"assets/image\\ui\\icon_up.png"
	},
	{
	"id":"info",
	"url":"assets/image\\ui\\info.png"
	},
	{
	"id":"info_panel",
	"url":"assets/image\\ui\\info_panel.png"
	},
	{
	"id":"loading_cat",
	"url":"assets/image\\ui\\loading_cat.png"
	},
	{
	"id":"loading_spinner",
	"url":"assets/image\\ui\\loading_spinner.png"
	},
	{
	"id":"morecats",
	"url":"assets/image\\ui\\morecats.png"
	},
	{
	"id":"new_item",
	"url":"assets/image\\ui\\new_item.png"
	},
	{
	"id":"onboarding_image",
	"url":"assets/image\\ui\\onboarding_image.png"
	},
	{
	"id":"open_silver_chest",
	"url":"assets/image\\ui\\open_silver_chest.png"
	},
	{
	"id":"planet_picture",
	"url":"assets/image\\ui\\planet_picture.png"
	},
	{
	"id":"play button_large_over",
	"url":"assets/image\\ui\\play button_large_over.png"
	},
	{
	"id":"play button_large_up",
	"url":"assets/image\\ui\\play button_large_up.png"
	},
	{
	"id":"powerbar_bar",
	"url":"assets/image\\ui\\powerbar_bar.png"
	},
	{
	"id":"powerbar_border",
	"url":"assets/image\\ui\\powerbar_border.png"
	},
	{
	"id":"powerup_background",
	"url":"assets/image\\ui\\powerup_background.png"
	},
	{
	"id":"powerup_background_on",
	"url":"assets/image\\ui\\powerup_background_on.png"
	},
	{
	"id":"progressbar_bar",
	"url":"assets/image\\ui\\progressbar_bar.png"
	},
	{
	"id":"progressbar_frame",
	"url":"assets/image\\ui\\progressbar_frame.png"
	},
	{
	"id":"rescue_cats",
	"url":"assets/image\\ui\\rescue_cats.png"
	},
	{
	"id":"results_arrow",
	"url":"assets/image\\ui\\results_arrow.png"
	},
	{
	"id":"results_lock",
	"url":"assets/image\\ui\\results_lock.png"
	},
	{
	"id":"results_locked_cat",
	"url":"assets/image\\ui\\results_locked_cat.png"
	},
	{
	"id":"results_newcat_glow",
	"url":"assets/image\\ui\\results_newcat_glow.png"
	},
	{
	"id":"results_newcat_rays_01",
	"url":"assets/image\\ui\\results_newcat_rays_01.png"
	},
	{
	"id":"results_newcat_rays_02",
	"url":"assets/image\\ui\\results_newcat_rays_02.png"
	},
	{
	"id":"results_newcat_star",
	"url":"assets/image\\ui\\results_newcat_star.png"
	},
	{
	"id":"rocket_button_off",
	"url":"assets/image\\ui\\rocket_button_off.png"
	},
	{
	"id":"rocket_button_over",
	"url":"assets/image\\ui\\rocket_button_over.png"
	},
	{
	"id":"rollerskate",
	"url":"assets/image\\ui\\rollerskate.png"
	},
	{
	"id":"round_back",
	"url":"assets/image\\ui\\round_back.png"
	},
	{
	"id":"score_plinth",
	"url":"assets/image\\ui\\score_plinth.png"
	},
	{
	"id":"spaceship",
	"url":"assets/image\\ui\\spaceship.png"
	},
	{
	"id":"text_auto_rescue",
	"url":"assets/image\\ui\\text_auto_rescue.png"
	},
	{
	"id":"text_catnip_frenzy",
	"url":"assets/image\\ui\\text_catnip_frenzy.png"
	},
	{
	"id":"text_double_points",
	"url":"assets/image\\ui\\text_double_points.png"
	},
	{
	"id":"text_super_speed",
	"url":"assets/image\\ui\\text_super_speed.png"
	},
	{
	"id":"text_you_won_prizes",
	"url":"assets/image\\ui\\text_you_won_prizes.png"
	},
	{
	"id":"token_grey",
	"url":"assets/image\\ui\\token_grey.png"
	},
	{
	"id":"token_price",
	"url":"assets/image\\ui\\token_price.png"
	},
	{
	"id":"token_quant",
	"url":"assets/image\\ui\\token_quant.png"
	},
	{
	"id":"treasure_chest",
	"url":"assets/image\\ui\\treasure_chest.png"
	},
	{
	"id":"treasure_chest_01",
	"url":"assets/image\\ui\\treasure_chest_01.png"
	},
	{
	"id":"treasure_chest_02",
	"url":"assets/image\\ui\\treasure_chest_02.png"
	},
	{
	"id":"treasure_chest_03",
	"url":"assets/image\\ui\\treasure_chest_03.png"
	},
	{
	"id":"trophy",
	"url":"assets/image\\ui\\trophy.png"
	},
	{
	"id":"ui_bg",
	"url":"assets/image\\ui\\ui_bg.png"
	},
	{
	"id":"video_rewards_automate",
	"url":"assets/image\\ui\\video_rewards_automate.png"
	},
	{
	"id":"video_rewards_shine",
	"url":"assets/image\\ui\\video_rewards_shine.png"
	},
	{
	"id":"video_rewards_title",
	"url":"assets/image\\ui\\video_rewards_title.png"
	},
	{
	"id":"video_rewards_video",
	"url":"assets/image\\ui\\video_rewards_video.png"
	},
	{
	"id":"video_reward_double_coins",
	"url":"assets/image\\ui\\video_reward_double_coins.png"
	},
	{
	"id":"helmet",
	"url":"assets/image\\cats\\helmet.png"
	},
	{
	"id":"cat_alien_arm",
	"url":"assets/image\\cats\\alien\\cat_alien_arm.png"
	},
	{
	"id":"cat_alien_body",
	"url":"assets/image\\cats\\alien\\cat_alien_body.png"
	},
	{
	"id":"cat_alien_head_01",
	"url":"assets/image\\cats\\alien\\cat_alien_head_01.png"
	},
	{
	"id":"cat_alien_leg",
	"url":"assets/image\\cats\\alien\\cat_alien_leg.png"
	},
	{
	"id":"cat_bowie_arm",
	"url":"assets/image\\cats\\bowie\\cat_bowie_arm.png"
	},
	{
	"id":"cat_bowie_body",
	"url":"assets/image\\cats\\bowie\\cat_bowie_body.png"
	},
	{
	"id":"cat_bowie_head_01",
	"url":"assets/image\\cats\\bowie\\cat_bowie_head_01.png"
	},
	{
	"id":"cat_bowie_leg",
	"url":"assets/image\\cats\\bowie\\cat_bowie_leg.png"
	},
	{
	"id":"cat_chef_arm",
	"url":"assets/image\\cats\\chef\\cat_chef_arm.png"
	},
	{
	"id":"cat_chef_body",
	"url":"assets/image\\cats\\chef\\cat_chef_body.png"
	},
	{
	"id":"cat_chef_head_01",
	"url":"assets/image\\cats\\chef\\cat_chef_head_01.png"
	},
	{
	"id":"cat_chef_leg",
	"url":"assets/image\\cats\\chef\\cat_chef_leg.png"
	},
	{
	"id":"cat_business_arm",
	"url":"assets/image\\cats\\business\\cat_business_arm.png"
	},
	{
	"id":"cat_business_body",
	"url":"assets/image\\cats\\business\\cat_business_body.png"
	},
	{
	"id":"cat_business_head_01",
	"url":"assets/image\\cats\\business\\cat_business_head_01.png"
	},
	{
	"id":"cat_business_leg",
	"url":"assets/image\\cats\\business\\cat_business_leg.png"
	},
	{
	"id":"cat_jeff_arm",
	"url":"assets/image\\cats\\cloud\\cat_jeff_arm.png"
	},
	{
	"id":"cat_jeff_body",
	"url":"assets/image\\cats\\cloud\\cat_jeff_body.png"
	},
	{
	"id":"cat_jeff_head_01",
	"url":"assets/image\\cats\\cloud\\cat_jeff_head_01.png"
	},
	{
	"id":"cat_jeff_leg",
	"url":"assets/image\\cats\\cloud\\cat_jeff_leg.png"
	},
	{
	"id":"cat_lucha_arm",
	"url":"assets/image\\cats\\lucha\\cat_lucha_arm.png"
	},
	{
	"id":"cat_lucha_body",
	"url":"assets/image\\cats\\lucha\\cat_lucha_body.png"
	},
	{
	"id":"cat_lucha_head_01",
	"url":"assets/image\\cats\\lucha\\cat_lucha_head_01.png"
	},
	{
	"id":"cat_lucha_leg",
	"url":"assets/image\\cats\\lucha\\cat_lucha_leg.png"
	},
	{
	"id":"cat_orange_arm",
	"url":"assets/image\\cats\\orange_cat\\cat_orange_arm.png"
	},
	{
	"id":"cat_orange_body",
	"url":"assets/image\\cats\\orange_cat\\cat_orange_body.png"
	},
	{
	"id":"cat_orange_head_01",
	"url":"assets/image\\cats\\orange_cat\\cat_orange_head_01.png"
	},
	{
	"id":"cat_orange_head_02",
	"url":"assets/image\\cats\\orange_cat\\cat_orange_head_02.png"
	},
	{
	"id":"cat_orange_head_03",
	"url":"assets/image\\cats\\orange_cat\\cat_orange_head_03.png"
	},
	{
	"id":"cat_orange_leg",
	"url":"assets/image\\cats\\orange_cat\\cat_orange_leg.png"
	},
	{
	"id":"cat_pink_arm",
	"url":"assets/image\\cats\\pink_cat\\cat_pink_arm.png"
	},
	{
	"id":"cat_pink_body",
	"url":"assets/image\\cats\\pink_cat\\cat_pink_body.png"
	},
	{
	"id":"cat_pink_head_01",
	"url":"assets/image\\cats\\pink_cat\\cat_pink_head_01.png"
	},
	{
	"id":"cat_pink_head_02",
	"url":"assets/image\\cats\\pink_cat\\cat_pink_head_02.png"
	},
	{
	"id":"cat_pink_head_03",
	"url":"assets/image\\cats\\pink_cat\\cat_pink_head_03.png"
	},
	{
	"id":"cat_pink_leg",
	"url":"assets/image\\cats\\pink_cat\\cat_pink_leg.png"
	},
	{
	"id":"cat_robot_arm",
	"url":"assets/image\\cats\\robot\\cat_robot_arm.png"
	},
	{
	"id":"cat_robot_body",
	"url":"assets/image\\cats\\robot\\cat_robot_body.png"
	},
	{
	"id":"cat_robot_head_01",
	"url":"assets/image\\cats\\robot\\cat_robot_head_01.png"
	},
	{
	"id":"cat_robot_leg",
	"url":"assets/image\\cats\\robot\\cat_robot_leg.png"
	},
	{
	"id":"cat_punk_arm",
	"url":"assets/image\\cats\\punk_cat\\cat_punk_arm.png"
	},
	{
	"id":"cat_punk_body",
	"url":"assets/image\\cats\\punk_cat\\cat_punk_body.png"
	},
	{
	"id":"cat_punk_head_01",
	"url":"assets/image\\cats\\punk_cat\\cat_punk_head_01.png"
	},
	{
	"id":"cat_punk_leg",
	"url":"assets/image\\cats\\punk_cat\\cat_punk_leg.png"
	},
	{
	"id":"cat_super_arm",
	"url":"assets/image\\cats\\super\\cat_super_arm.png"
	},
	{
	"id":"cat_super_body",
	"url":"assets/image\\cats\\super\\cat_super_body.png"
	},
	{
	"id":"cat_super_head_01",
	"url":"assets/image\\cats\\super\\cat_super_head_01.png"
	},
	{
	"id":"cat_super_leg",
	"url":"assets/image\\cats\\super\\cat_super_leg.png"
	},
	{
	"id":"cat_snake_arm",
	"url":"assets/image\\cats\\snake\\cat_snake_arm.png"
	},
	{
	"id":"cat_snake_body",
	"url":"assets/image\\cats\\snake\\cat_snake_body.png"
	},
	{
	"id":"cat_snake_head_01",
	"url":"assets/image\\cats\\snake\\cat_snake_head_01.png"
	},
	{
	"id":"cat_snake_leg",
	"url":"assets/image\\cats\\snake\\cat_snake_leg.png"
	},
	{
	"id":"cat_surf_arm",
	"url":"assets/image\\cats\\surf\\cat_surf_arm.png"
	},
	{
	"id":"cat_surf_body",
	"url":"assets/image\\cats\\surf\\cat_surf_body.png"
	},
	{
	"id":"cat_surf_head_01",
	"url":"assets/image\\cats\\surf\\cat_surf_head_01.png"
	},
	{
	"id":"cat_surf_leg",
	"url":"assets/image\\cats\\surf\\cat_surf_leg.png"
	},
	{
	"id":"cat_turquoise_arm",
	"url":"assets/image\\cats\\turquoise_cat\\cat_turquoise_arm.png"
	},
	{
	"id":"cat_turquoise_body",
	"url":"assets/image\\cats\\turquoise_cat\\cat_turquoise_body.png"
	},
	{
	"id":"cat_turquoise_head_01",
	"url":"assets/image\\cats\\turquoise_cat\\cat_turquoise_head_01.png"
	},
	{
	"id":"cat_turquoise_head_02",
	"url":"assets/image\\cats\\turquoise_cat\\cat_turquoise_head_02.png"
	},
	{
	"id":"cat_turquoise_head_03",
	"url":"assets/image\\cats\\turquoise_cat\\cat_turquoise_head_03.png"
	},
	{
	"id":"cat_turquoise_leg",
	"url":"assets/image\\cats\\turquoise_cat\\cat_turquoise_leg.png"
	},
	{
	"id":"cat_ufo_arm",
	"url":"assets/image\\cats\\ufo\\cat_ufo_arm.png"
	},
	{
	"id":"cat_ufo_body",
	"url":"assets/image\\cats\\ufo\\cat_ufo_body.png"
	},
	{
	"id":"cat_ufo_head_01",
	"url":"assets/image\\cats\\ufo\\cat_ufo_head_01.png"
	},
	{
	"id":"cat_ufo_leg",
	"url":"assets/image\\cats\\ufo\\cat_ufo_leg.png"
	},
	{
	"id":"white_arm",
	"url":"assets/image\\cats\\white_cat\\white_arm.png"
	},
	{
	"id":"white_body",
	"url":"assets/image\\cats\\white_cat\\white_body.png"
	},
	{
	"id":"white_head_01",
	"url":"assets/image\\cats\\white_cat\\white_head_01.png"
	},
	{
	"id":"white_head_02",
	"url":"assets/image\\cats\\white_cat\\white_head_02.png"
	},
	{
	"id":"white_head_03",
	"url":"assets/image\\cats\\white_cat\\white_head_03.png"
	},
	{
	"id":"white_leg",
	"url":"assets/image\\cats\\white_cat\\white_leg.png"
	},
	{
	"id":"cat_yellow_arm",
	"url":"assets/image\\cats\\yellow_cat\\cat_yellow_arm.png"
	},
	{
	"id":"cat_yellow_body",
	"url":"assets/image\\cats\\yellow_cat\\cat_yellow_body.png"
	},
	{
	"id":"cat_yellow_head_01",
	"url":"assets/image\\cats\\yellow_cat\\cat_yellow_head_01.png"
	},
	{
	"id":"cat_yellow_head_02",
	"url":"assets/image\\cats\\yellow_cat\\cat_yellow_head_02.png"
	},
	{
	"id":"cat_yellow_head_03",
	"url":"assets/image\\cats\\yellow_cat\\cat_yellow_head_03.png"
	},
	{
	"id":"cat_yellow_leg",
	"url":"assets/image\\cats\\yellow_cat\\cat_yellow_leg.png"
	}
];

export default assets;
