const assets = [
	{
	"id":"boing",
	"url":"assets/audio/boing.ogg"
	},
	{
	"id":"cat_02",
	"url":"assets/audio/cat_02.ogg"
	},
	{
	"id":"button_click",
	"url":"assets/audio/button_click.ogg"
	},
	{
	"id":"cat_01",
	"url":"assets/audio/cat_01.ogg"
	},
	{
	"id":"cat_03",
	"url":"assets/audio/cat_03.ogg"
	},
	{
	"id":"cat_04",
	"url":"assets/audio/cat_04.ogg"
	},
	{
	"id":"cat_06",
	"url":"assets/audio/cat_06.ogg"
	},
	{
	"id":"cat_05",
	"url":"assets/audio/cat_05.ogg"
	},
	{
	"id":"cat_07",
	"url":"assets/audio/cat_07.ogg"
	},
	{
	"id":"cat_08",
	"url":"assets/audio/cat_08.ogg"
	},
	{
	"id":"cat_09",
	"url":"assets/audio/cat_09.ogg"
	},
	{
	"id":"cat_10",
	"url":"assets/audio/cat_10.ogg"
	},
	{
	"id":"coins_01",
	"url":"assets/audio/coins_01.ogg"
	},
	{
	"id":"coins_02",
	"url":"assets/audio/coins_02.ogg"
	},
	{
	"id":"coins_03",
	"url":"assets/audio/coins_03.ogg"
	},
	{
	"id":"coins_04",
	"url":"assets/audio/coins_04.ogg"
	},
	{
	"id":"dream1",
	"url":"assets/audio/dream1.ogg"
	},
	{
	"id":"dream2",
	"url":"assets/audio/dream2.ogg"
	},
	{
	"id":"getstar",
	"url":"assets/audio/getstar.ogg"
	},
	{
	"id":"grind",
	"url":"assets/audio/grind.wav"
	},
	{
	"id":"pickup",
	"url":"assets/audio/pickup.ogg"
	},
	{
	"id":"pickup_item2",
	"url":"assets/audio/pickup_item2.ogg"
	},
	{
	"id":"pickup_present",
	"url":"assets/audio/pickup_present.ogg"
	},
	{
	"id":"pickup_star",
	"url":"assets/audio/pickup_star.ogg"
	},
	{
	"id":"pogo_boing",
	"url":"assets/audio/pogo_boing.ogg"
	},
	{
	"id":"pop",
	"url":"assets/audio/pop.ogg"
	},
	{
	"id":"rocket_launch_01",
	"url":"assets/audio/rocket_launch_01.ogg"
	},
	{
	"id":"score_loop",
	"url":"assets/audio/score_loop.ogg"
	},
	{
	"id":"spacecat_game_music",
	"url":"assets/audio/spacecat_game_music.ogg"
	},
	{
	"id":"spacecat_menu_music",
	"url":"assets/audio/spacecat_menu_music.ogg"
	},
	{
	"id":"star_01",
	"url":"assets/audio/star_01.ogg"
	},
	{
	"id":"star_02",
	"url":"assets/audio/star_02.ogg"
	},
	{
	"id":"star_03",
	"url":"assets/audio/star_03.ogg"
	},
	{
	"id":"teleport",
	"url":"assets/audio/teleport.ogg"
	}
];

export default assets;
