const assets = [
	{
	"id":"base-gradient",
	"url":"assets/image\\base-gradient.png"
	},
	{
	"id":"bigblur",
	"url":"assets/image\\bigblur.png"
	},
	{
	"id":"cat_01",
	"url":"assets/image\\cat_01.png"
	},
	{
	"id":"cat_head",
	"url":"assets/image\\cat_head.png"
	},
	{
	"id":"glass",
	"url":"assets/image\\glass.png"
	},
	{
	"id":"image",
	"url":"assets/image\\image.png"
	},
	{
	"id":"lane_texture - Copy",
	"url":"assets/image\\lane_texture - Copy.png"
	},
	{
	"id":"lane_texture",
	"url":"assets/image\\lane_texture.png"
	},
	{
	"id":"lettering",
	"url":"assets/image\\lettering.png"
	},
	{
	"id":"logo",
	"url":"assets/image\\logo.png"
	},
	{
	"id":"logo_mask",
	"url":"assets/image\\logo_mask.png"
	},
	{
	"id":"logo_mask_white",
	"url":"assets/image\\logo_mask_white.png"
	},
	{
	"id":"pattern",
	"url":"assets/image\\pattern.png"
	},
	{
	"id":"planet",
	"url":"assets/image\\planet.png"
	},
	{
	"id":"planet1",
	"url":"assets/image\\planet1.png"
	},
	{
	"id":"planet2",
	"url":"assets/image\\planet2.png"
	},
	{
	"id":"planet3",
	"url":"assets/image\\planet3.png"
	},
	{
	"id":"planet4",
	"url":"assets/image\\planet4.png"
	},
	{
	"id":"vignette-tex",
	"url":"assets/image\\vignette-tex.png"
	},
	{
	"id":"vignette-tex2",
	"url":"assets/image\\vignette-tex2.png"
	},
	{
	"id":"vignette",
	"url":"assets/image\\vignette.png"
	},
	{
	"id":"spark2",
	"url":"assets/image\\particles\\spark2.png"
	},
	{
	"id":"cat_orange_00000",
	"url":"assets/image\\frames\\cat_orange_00000.png"
	},
	{
	"id":"cat_orange_00001",
	"url":"assets/image\\frames\\cat_orange_00001.png"
	},
	{
	"id":"cat_orange_00002",
	"url":"assets/image\\frames\\cat_orange_00002.png"
	},
	{
	"id":"cat_orange_00003",
	"url":"assets/image\\frames\\cat_orange_00003.png"
	},
	{
	"id":"cat_orange_00004",
	"url":"assets/image\\frames\\cat_orange_00004.png"
	},
	{
	"id":"cat_orange_00005",
	"url":"assets/image\\frames\\cat_orange_00005.png"
	},
	{
	"id":"cat_orange_00006",
	"url":"assets/image\\frames\\cat_orange_00006.png"
	},
	{
	"id":"cat_orange_00007",
	"url":"assets/image\\frames\\cat_orange_00007.png"
	},
	{
	"id":"cat_orange_00008",
	"url":"assets/image\\frames\\cat_orange_00008.png"
	},
	{
	"id":"cat_orange_00009",
	"url":"assets/image\\frames\\cat_orange_00009.png"
	},
	{
	"id":"cat_orange_00010",
	"url":"assets/image\\frames\\cat_orange_00010.png"
	},
	{
	"id":"cat_orange_00011",
	"url":"assets/image\\frames\\cat_orange_00011.png"
	},
	{
	"id":"cat_orange_00012",
	"url":"assets/image\\frames\\cat_orange_00012.png"
	},
	{
	"id":"cat_orange_00013",
	"url":"assets/image\\frames\\cat_orange_00013.png"
	},
	{
	"id":"cat_orange_00014",
	"url":"assets/image\\frames\\cat_orange_00014.png"
	},
	{
	"id":"cat_orange_00015",
	"url":"assets/image\\frames\\cat_orange_00015.png"
	},
	{
	"id":"cat_orange_00016",
	"url":"assets/image\\frames\\cat_orange_00016.png"
	},
	{
	"id":"cat_orange_00017",
	"url":"assets/image\\frames\\cat_orange_00017.png"
	},
	{
	"id":"cat_orange_00018",
	"url":"assets/image\\frames\\cat_orange_00018.png"
	},
	{
	"id":"cat_orange_00019",
	"url":"assets/image\\frames\\cat_orange_00019.png"
	},
	{
	"id":"cat_pink_00000",
	"url":"assets/image\\frames\\cat_pink_00000.png"
	},
	{
	"id":"cat_pink_00001",
	"url":"assets/image\\frames\\cat_pink_00001.png"
	},
	{
	"id":"cat_pink_00002",
	"url":"assets/image\\frames\\cat_pink_00002.png"
	},
	{
	"id":"cat_pink_00003",
	"url":"assets/image\\frames\\cat_pink_00003.png"
	},
	{
	"id":"cat_pink_00004",
	"url":"assets/image\\frames\\cat_pink_00004.png"
	},
	{
	"id":"cat_pink_00005",
	"url":"assets/image\\frames\\cat_pink_00005.png"
	},
	{
	"id":"cat_pink_00006",
	"url":"assets/image\\frames\\cat_pink_00006.png"
	},
	{
	"id":"cat_pink_00007",
	"url":"assets/image\\frames\\cat_pink_00007.png"
	},
	{
	"id":"cat_pink_00008",
	"url":"assets/image\\frames\\cat_pink_00008.png"
	},
	{
	"id":"cat_pink_00009",
	"url":"assets/image\\frames\\cat_pink_00009.png"
	},
	{
	"id":"cat_pink_00010",
	"url":"assets/image\\frames\\cat_pink_00010.png"
	},
	{
	"id":"cat_pink_00011",
	"url":"assets/image\\frames\\cat_pink_00011.png"
	},
	{
	"id":"cat_pink_00012",
	"url":"assets/image\\frames\\cat_pink_00012.png"
	},
	{
	"id":"cat_pink_00013",
	"url":"assets/image\\frames\\cat_pink_00013.png"
	},
	{
	"id":"cat_pink_00014",
	"url":"assets/image\\frames\\cat_pink_00014.png"
	},
	{
	"id":"cat_pink_00015",
	"url":"assets/image\\frames\\cat_pink_00015.png"
	},
	{
	"id":"cat_pink_00016",
	"url":"assets/image\\frames\\cat_pink_00016.png"
	},
	{
	"id":"cat_pink_00017",
	"url":"assets/image\\frames\\cat_pink_00017.png"
	},
	{
	"id":"cat_pink_00018",
	"url":"assets/image\\frames\\cat_pink_00018.png"
	},
	{
	"id":"cat_pink_00019",
	"url":"assets/image\\frames\\cat_pink_00019.png"
	},
	{
	"id":"cat_turquoise_00000",
	"url":"assets/image\\frames\\cat_turquoise_00000.png"
	},
	{
	"id":"cat_turquoise_00001",
	"url":"assets/image\\frames\\cat_turquoise_00001.png"
	},
	{
	"id":"cat_turquoise_00002",
	"url":"assets/image\\frames\\cat_turquoise_00002.png"
	},
	{
	"id":"cat_turquoise_00003",
	"url":"assets/image\\frames\\cat_turquoise_00003.png"
	},
	{
	"id":"cat_turquoise_00004",
	"url":"assets/image\\frames\\cat_turquoise_00004.png"
	},
	{
	"id":"cat_turquoise_00005",
	"url":"assets/image\\frames\\cat_turquoise_00005.png"
	},
	{
	"id":"cat_turquoise_00006",
	"url":"assets/image\\frames\\cat_turquoise_00006.png"
	},
	{
	"id":"cat_turquoise_00007",
	"url":"assets/image\\frames\\cat_turquoise_00007.png"
	},
	{
	"id":"cat_turquoise_00008",
	"url":"assets/image\\frames\\cat_turquoise_00008.png"
	},
	{
	"id":"cat_turquoise_00009",
	"url":"assets/image\\frames\\cat_turquoise_00009.png"
	},
	{
	"id":"cat_turquoise_00010",
	"url":"assets/image\\frames\\cat_turquoise_00010.png"
	},
	{
	"id":"cat_turquoise_00011",
	"url":"assets/image\\frames\\cat_turquoise_00011.png"
	},
	{
	"id":"cat_turquoise_00012",
	"url":"assets/image\\frames\\cat_turquoise_00012.png"
	},
	{
	"id":"cat_turquoise_00013",
	"url":"assets/image\\frames\\cat_turquoise_00013.png"
	},
	{
	"id":"cat_turquoise_00014",
	"url":"assets/image\\frames\\cat_turquoise_00014.png"
	},
	{
	"id":"cat_turquoise_00015",
	"url":"assets/image\\frames\\cat_turquoise_00015.png"
	},
	{
	"id":"cat_turquoise_00016",
	"url":"assets/image\\frames\\cat_turquoise_00016.png"
	},
	{
	"id":"cat_turquoise_00017",
	"url":"assets/image\\frames\\cat_turquoise_00017.png"
	},
	{
	"id":"cat_turquoise_00018",
	"url":"assets/image\\frames\\cat_turquoise_00018.png"
	},
	{
	"id":"cat_turquoise_00019",
	"url":"assets/image\\frames\\cat_turquoise_00019.png"
	},
	{
	"id":"cat_yellow_00000",
	"url":"assets/image\\frames\\cat_yellow_00000.png"
	},
	{
	"id":"cat_yellow_00001",
	"url":"assets/image\\frames\\cat_yellow_00001.png"
	},
	{
	"id":"cat_yellow_00002",
	"url":"assets/image\\frames\\cat_yellow_00002.png"
	},
	{
	"id":"cat_yellow_00003",
	"url":"assets/image\\frames\\cat_yellow_00003.png"
	},
	{
	"id":"cat_yellow_00004",
	"url":"assets/image\\frames\\cat_yellow_00004.png"
	},
	{
	"id":"cat_yellow_00005",
	"url":"assets/image\\frames\\cat_yellow_00005.png"
	},
	{
	"id":"cat_yellow_00006",
	"url":"assets/image\\frames\\cat_yellow_00006.png"
	},
	{
	"id":"cat_yellow_00007",
	"url":"assets/image\\frames\\cat_yellow_00007.png"
	},
	{
	"id":"cat_yellow_00008",
	"url":"assets/image\\frames\\cat_yellow_00008.png"
	},
	{
	"id":"cat_yellow_00009",
	"url":"assets/image\\frames\\cat_yellow_00009.png"
	},
	{
	"id":"cat_yellow_00010",
	"url":"assets/image\\frames\\cat_yellow_00010.png"
	},
	{
	"id":"cat_yellow_00011",
	"url":"assets/image\\frames\\cat_yellow_00011.png"
	},
	{
	"id":"cat_yellow_00012",
	"url":"assets/image\\frames\\cat_yellow_00012.png"
	},
	{
	"id":"cat_yellow_00013",
	"url":"assets/image\\frames\\cat_yellow_00013.png"
	},
	{
	"id":"cat_yellow_00014",
	"url":"assets/image\\frames\\cat_yellow_00014.png"
	},
	{
	"id":"cat_yellow_00015",
	"url":"assets/image\\frames\\cat_yellow_00015.png"
	},
	{
	"id":"cat_yellow_00016",
	"url":"assets/image\\frames\\cat_yellow_00016.png"
	},
	{
	"id":"cat_yellow_00017",
	"url":"assets/image\\frames\\cat_yellow_00017.png"
	},
	{
	"id":"cat_yellow_00018",
	"url":"assets/image\\frames\\cat_yellow_00018.png"
	},
	{
	"id":"cat_yellow_00019",
	"url":"assets/image\\frames\\cat_yellow_00019.png"
	},
	{
	"id":"pickup_bubble",
	"url":"assets/image\\pickups\\pickup_bubble.png"
	},
	{
	"id":"pickup_fish",
	"url":"assets/image\\pickups\\pickup_fish.png"
	},
	{
	"id":"pickup_mouse",
	"url":"assets/image\\pickups\\pickup_mouse.png"
	},
	{
	"id":"pickup_octopus",
	"url":"assets/image\\pickups\\pickup_octopus.png"
	},
	{
	"id":"active_engine",
	"url":"assets/image\\ui\\active_engine.png"
	},
	{
	"id":"auto_collect_action",
	"url":"assets/image\\ui\\auto_collect_action.png"
	},
	{
	"id":"auto_confirm",
	"url":"assets/image\\ui\\auto_confirm.png"
	},
	{
	"id":"back_button",
	"url":"assets/image\\ui\\back_button.png"
	},
	{
	"id":"bubble",
	"url":"assets/image\\ui\\bubble.png"
	},
	{
	"id":"buy_grey",
	"url":"assets/image\\ui\\buy_grey.png"
	},
	{
	"id":"buy_icon",
	"url":"assets/image\\ui\\buy_icon.png"
	},
	{
	"id":"cat_coin",
	"url":"assets/image\\ui\\cat_coin.png"
	},
	{
	"id":"deactive_engine",
	"url":"assets/image\\ui\\deactive_engine.png"
	},
	{
	"id":"double_points_action",
	"url":"assets/image\\ui\\double_points_action.png"
	},
	{
	"id":"double_speed_action",
	"url":"assets/image\\ui\\double_speed_action.png"
	},
	{
	"id":"engine_icon",
	"url":"assets/image\\ui\\engine_icon.png"
	},
	{
	"id":"game_button_base",
	"url":"assets/image\\ui\\game_button_base.png"
	},
	{
	"id":"game_button_base_borderless",
	"url":"assets/image\\ui\\game_button_base_borderless.png"
	},
	{
	"id":"game_button_base_borderless_green",
	"url":"assets/image\\ui\\game_button_base_borderless_green.png"
	},
	{
	"id":"game_button_off",
	"url":"assets/image\\ui\\game_button_off.png"
	},
	{
	"id":"game_button_on",
	"url":"assets/image\\ui\\game_button_on.png"
	},
	{
	"id":"goodboy",
	"url":"assets/image\\ui\\goodboy.png"
	},
	{
	"id":"goodboy_logo",
	"url":"assets/image\\ui\\goodboy_logo.png"
	},
	{
	"id":"icon_border",
	"url":"assets/image\\ui\\icon_border.png"
	},
	{
	"id":"icon_lives",
	"url":"assets/image\\ui\\icon_lives.png"
	},
	{
	"id":"icon_paw",
	"url":"assets/image\\ui\\icon_paw.png"
	},
	{
	"id":"info",
	"url":"assets/image\\ui\\info.png"
	},
	{
	"id":"play button_large_over",
	"url":"assets/image\\ui\\play button_large_over.png"
	},
	{
	"id":"play button_large_up",
	"url":"assets/image\\ui\\play button_large_up.png"
	},
	{
	"id":"powerbar_bar",
	"url":"assets/image\\ui\\powerbar_bar.png"
	},
	{
	"id":"powerbar_border",
	"url":"assets/image\\ui\\powerbar_border.png"
	},
	{
	"id":"results_arrow",
	"url":"assets/image\\ui\\results_arrow.png"
	},
	{
	"id":"results_lock",
	"url":"assets/image\\ui\\results_lock.png"
	},
	{
	"id":"results_newcat_glow",
	"url":"assets/image\\ui\\results_newcat_glow.png"
	},
	{
	"id":"results_newcat_rays_01",
	"url":"assets/image\\ui\\results_newcat_rays_01.png"
	},
	{
	"id":"results_newcat_rays_02",
	"url":"assets/image\\ui\\results_newcat_rays_02.png"
	},
	{
	"id":"results_newcat_star",
	"url":"assets/image\\ui\\results_newcat_star.png"
	},
	{
	"id":"results_orange_cat",
	"url":"assets/image\\ui\\results_orange_cat.png"
	},
	{
	"id":"results_locked_cat",
	"url":"assets/image\\ui\\results_locked_cat.png"
	},
	{
	"id":"results_pink_cat",
	"url":"assets/image\\ui\\results_pink_cat.png"
	},
	{
	"id":"results_turquoise_cat",
	"url":"assets/image\\ui\\results_turquoise_cat.png"
	},
	{
	"id":"results_yellow_cat",
	"url":"assets/image\\ui\\results_yellow_cat.png"
	},
	{
	"id":"rocket_button_off",
	"url":"assets/image\\ui\\rocket_button_off.png"
	},
	{
	"id":"rocket_button_over",
	"url":"assets/image\\ui\\rocket_button_over.png"
	},
	{
	"id":"round_back",
	"url":"assets/image\\ui\\round_back.png"
	},
	{
	"id":"score_plinth",
	"url":"assets/image\\ui\\score_plinth.png"
	},
	{
	"id":"shop_button",
	"url":"assets/image\\ui\\shop_button.png"
	},
	{
	"id":"spaceship",
	"url":"assets/image\\ui\\spaceship.png"
	},
	{
	"id":"text_catnip_frenzy",
	"url":"assets/image\\ui\\text_catnip_frenzy.png"
	},
	{
	"id":"token_grey",
	"url":"assets/image\\ui\\token_grey.png"
	},
	{
	"id":"token_price",
	"url":"assets/image\\ui\\token_price.png"
	},
	{
	"id":"token_quant",
	"url":"assets/image\\ui\\token_quant.png"
	},
	{
	"id":"ui_bg",
	"url":"assets/image\\ui\\ui_bg.png"
	},
	{
	"id":"video_icon",
	"url":"assets/image\\ui\\video_icon.png"
	},
	{
	"id":"text_auto_rescue",
	"url":"assets/image\\ui\\text_auto_rescue.png"
	},
	{
	"id":"cat_orange_arm",
	"url":"assets/image\\cats\\orange_cat\\cat_orange_arm.png"
	},
	{
	"id":"cat_orange_belly",
	"url":"assets/image\\cats\\orange_cat\\cat_orange_belly.png"
	},
	{
	"id":"cat_orange_head",
	"url":"assets/image\\cats\\orange_cat\\cat_orange_head.png"
	},
	{
	"id":"cat_orange_leg",
	"url":"assets/image\\cats\\orange_cat\\cat_orange_leg.png"
	},
	{
	"id":"cat_pink_arm",
	"url":"assets/image\\cats\\pink_cat\\cat_pink_arm.png"
	},
	{
	"id":"cat_pink_belly",
	"url":"assets/image\\cats\\pink_cat\\cat_pink_belly.png"
	},
	{
	"id":"cat_pink_head",
	"url":"assets/image\\cats\\pink_cat\\cat_pink_head.png"
	},
	{
	"id":"cat_pink_leg",
	"url":"assets/image\\cats\\pink_cat\\cat_pink_leg.png"
	},
	{
	"id":"white_arm",
	"url":"assets/image\\cats\\white_cat\\white_arm.png"
	},
	{
	"id":"white_belly",
	"url":"assets/image\\cats\\white_cat\\white_belly.png"
	},
	{
	"id":"white_head",
	"url":"assets/image\\cats\\white_cat\\white_head.png"
	},
	{
	"id":"white_leg",
	"url":"assets/image\\cats\\white_cat\\white_leg.png"
	}
];

export default assets;
