const assets = [
	{
	"id":"boing",
	"url":"assets/audio\\boing.mp3"
	},
	{
	"id":"button_click",
	"url":"assets/audio\\button_click.mp3"
	},
	{
	"id":"cat_01",
	"url":"assets/audio\\cat_01.mp3"
	},
	{
	"id":"cat_02",
	"url":"assets/audio\\cat_02.mp3"
	},
	{
	"id":"cat_03",
	"url":"assets/audio\\cat_03.mp3"
	},
	{
	"id":"cat_04",
	"url":"assets/audio\\cat_04.mp3"
	},
	{
	"id":"cat_05",
	"url":"assets/audio\\cat_05.mp3"
	},
	{
	"id":"cat_06",
	"url":"assets/audio\\cat_06.mp3"
	},
	{
	"id":"cat_07",
	"url":"assets/audio\\cat_07.mp3"
	},
	{
	"id":"cat_08",
	"url":"assets/audio\\cat_08.mp3"
	},
	{
	"id":"cat_09",
	"url":"assets/audio\\cat_09.mp3"
	},
	{
	"id":"cat_fall_02",
	"url":"assets/audio\\cat_fall_02.mp3"
	},
	{
	"id":"cat_fall_01",
	"url":"assets/audio\\cat_fall_01.mp3"
	},
	{
	"id":"cat_10",
	"url":"assets/audio\\cat_10.mp3"
	},
	{
	"id":"cat_fall_03",
	"url":"assets/audio\\cat_fall_03.mp3"
	},
	{
	"id":"coins_01",
	"url":"assets/audio\\coins_01.mp3"
	},
	{
	"id":"coins_02",
	"url":"assets/audio\\coins_02.mp3"
	},
	{
	"id":"coins_03",
	"url":"assets/audio\\coins_03.mp3"
	},
	{
	"id":"coins_04",
	"url":"assets/audio\\coins_04.mp3"
	},
	{
	"id":"fastforward",
	"url":"assets/audio\\fastforward.mp3"
	},
	{
	"id":"getstar",
	"url":"assets/audio\\getstar.mp3"
	},
	{
	"id":"pickup_item2",
	"url":"assets/audio\\pickup_item2.mp3"
	},
	{
	"id":"pickup",
	"url":"assets/audio\\pickup.mp3"
	},
	{
	"id":"open_chest_01",
	"url":"assets/audio\\open_chest_01.mp3"
	},
	{
	"id":"pickup_present",
	"url":"assets/audio\\pickup_present.mp3"
	},
	{
	"id":"pogo_boing",
	"url":"assets/audio\\pogo_boing.mp3"
	},
	{
	"id":"pickup_star",
	"url":"assets/audio\\pickup_star.mp3"
	},
	{
	"id":"rocket_launch_01",
	"url":"assets/audio\\rocket_launch_01.mp3"
	},
	{
	"id":"pop",
	"url":"assets/audio\\pop.mp3"
	},
	{
	"id":"score_loop",
	"url":"assets/audio\\score_loop.mp3"
	},
	{
	"id":"spacecat_menu_music",
	"url":"assets/audio\\spacecat_menu_music.mp3"
	},
	{
	"id":"star_01",
	"url":"assets/audio\\star_01.mp3"
	},
	{
	"id":"spacecat_game_music",
	"url":"assets/audio\\spacecat_game_music.mp3"
	},
	{
	"id":"star_02",
	"url":"assets/audio\\star_02.mp3"
	},
	{
	"id":"star_03",
	"url":"assets/audio\\star_03.mp3"
	},
	{
	"id":"teleport",
	"url":"assets/audio\\teleport.mp3"
	}
];

export default assets;
